services:
  v-b-database:
    image: postgres
    restart: always
    container_name: v-b-database
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=v-b
    ports:
      - '5432:5432'
    volumes:
      - v-b-database:/var/lib/postgresql/data

  v-b-backend:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    container_name: v-b-backend
    ports:
      - "8080:8080"
    depends_on:
      - v-b-database
    volumes:
      - .:/app

volumes:
  v-b-database: