"""Added unique key constraint on social_medias tables.

Revision ID: abd62f2ab124
Revises: b57925545422
Create Date: 2025-04-24 12:38:56.377235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'abd62f2ab124'
down_revision: Union[str, None] = 'b57925545422'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('events_social_media_unique_constraint', 'events_social_medias', ['event_id', 'type'])
    op.create_unique_constraint('restaurants_social_media_unique_constraint', 'restaurants_social_medias', ['restaurant_id', 'type'])
    op.create_unique_constraint('accommodations_social_media_unique_constraint', 'accommodations_social_medias', ['accommodation_id', 'type'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accommodations_social_media_unique_constraint', 'accommodations_social_medias', type_='unique')
    op.drop_constraint('restaurants_social_media_unique_constraint', 'restaurants_social_medias', type_='unique')
    op.drop_constraint('events_social_media_unique_constraint', 'events_social_medias', type_='unique')
    # ### end Alembic commands ###
