"""Added and defined ondelete action to foreign key columns.

Revision ID: b57925545422
Revises: 791eb9b7052f
Create Date: 2025-04-23 13:28:07.120241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57925545422'
down_revision: Union[str, None] = '791eb9b7052f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('accommodations_city_id_fkey', 'accommodations', type_='foreignkey')
    op.drop_constraint('accommodations_landmark_id_fkey', 'accommodations', type_='foreignkey')
    op.create_foreign_key(None, 'accommodations', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'accommodations', 'landmarks', ['landmark_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('accommodations_social_medias_accommodation_id_fkey', 'accommodations_social_medias', type_='foreignkey')
    op.create_foreign_key(None, 'accommodations_social_medias', 'accommodations', ['accommodation_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('events_landmark_id_fkey', 'events', type_='foreignkey')
    op.drop_constraint('events_city_id_fkey', 'events', type_='foreignkey')
    op.create_foreign_key(None, 'events', 'landmarks', ['landmark_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'events', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('events_social_medias_event_id_fkey', 'events_social_medias', type_='foreignkey')
    op.create_foreign_key(None, 'events_social_medias', 'events', ['event_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('landmarks_city_id_fkey', 'landmarks', type_='foreignkey')
    op.create_foreign_key(None, 'landmarks', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('restaurants_landmark_id_fkey', 'restaurants', type_='foreignkey')
    op.drop_constraint('restaurants_city_id_fkey', 'restaurants', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants', 'cities', ['city_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'restaurants', 'landmarks', ['landmark_id'], ['id'], ondelete='SET NULL')
    op.drop_constraint('restaurants_social_medias_restaurant_id_fkey', 'restaurants_social_medias', type_='foreignkey')
    op.create_foreign_key(None, 'restaurants_social_medias', 'restaurants', ['restaurant_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'restaurants_social_medias', type_='foreignkey')
    op.create_foreign_key('restaurants_social_medias_restaurant_id_fkey', 'restaurants_social_medias', 'restaurants', ['restaurant_id'], ['id'])
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.drop_constraint(None, 'restaurants', type_='foreignkey')
    op.create_foreign_key('restaurants_city_id_fkey', 'restaurants', 'cities', ['city_id'], ['id'])
    op.create_foreign_key('restaurants_landmark_id_fkey', 'restaurants', 'landmarks', ['landmark_id'], ['id'])
    op.drop_constraint(None, 'landmarks', type_='foreignkey')
    op.create_foreign_key('landmarks_city_id_fkey', 'landmarks', 'cities', ['city_id'], ['id'])
    op.drop_constraint(None, 'events_social_medias', type_='foreignkey')
    op.create_foreign_key('events_social_medias_event_id_fkey', 'events_social_medias', 'events', ['event_id'], ['id'])
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.drop_constraint(None, 'events', type_='foreignkey')
    op.create_foreign_key('events_city_id_fkey', 'events', 'cities', ['city_id'], ['id'])
    op.create_foreign_key('events_landmark_id_fkey', 'events', 'landmarks', ['landmark_id'], ['id'])
    op.drop_constraint(None, 'accommodations_social_medias', type_='foreignkey')
    op.create_foreign_key('accommodations_social_medias_accommodation_id_fkey', 'accommodations_social_medias', 'accommodations', ['accommodation_id'], ['id'])
    op.drop_constraint(None, 'accommodations', type_='foreignkey')
    op.drop_constraint(None, 'accommodations', type_='foreignkey')
    op.create_foreign_key('accommodations_landmark_id_fkey', 'accommodations', 'landmarks', ['landmark_id'], ['id'])
    op.create_foreign_key('accommodations_city_id_fkey', 'accommodations', 'cities', ['city_id'], ['id'])
    # ### end Alembic commands ###
